{{- $vm := .Values.VirtualMachine -}}
{{- range $i, $e := until (int $vm.count) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fakefish-{{ printf "%s-%02d" $vm.baseName $i }}-{{ $.Release.Namespace }}
  namespace: {{ $.Release.Namespace }}
  labels:
{{- range $key, $value := $.Values.common.metadata.labels }}
    {{ $key }}: {{ $value }}
{{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fakefish-{{ printf "%s-%02d" $vm.baseName $i }}-{{ $.Release.Namespace }}
  template:
    metadata:
      labels:
        app: fakefish-{{ printf "%s-%02d" $vm.baseName $i }}-{{ $.Release.Namespace }}
    spec:
      serviceAccountName: {{ $.Release.Namespace }}-serviceaccount
      containers:
        - name: fakefish
          image: {{ $.Values.fakefish.image }}
          args:
            - '--remote-bmc'
            - {{ printf "%s-%02d" $vm.baseName $i }}_{{ $.Release.Namespace }}
            - '--tls-mode'
            - disabled
{{- end }}
