---
apiVersion: v1
kind: Secret
metadata:
  name: fakefish-kubevirt-kubeconfig
  namespace: {{ .Release.Namespace }}
  labels:
{{- range $key, $value := .Values.common.metadata.labels }}
    {{ $key }}: {{ $value }}
{{- end }}
data:
  kubeconfig: {{ .Values.secret.kubeconfigContent }}