apiVersion: v2
name: ocp-on-cnv
description: This helm chart can be used to deploy OpenShift on top of OpenShift Virtualization using OpenShift's BMO and Fakefish.
type: application
version: 0.1.0
appVersion: "1.0"