---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Release.Namespace }}-serviceaccount
  namespace: {{ $.Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $.Release.Namespace }}-admin-role
  namespace: {{ $.Release.Namespace }}
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $.Release.Namespace }}-serviceaccount-bind
  namespace: {{ $.Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ $.Release.Namespace }}-serviceaccount
roleRef:
  kind: Role
  name: {{ $.Release.Namespace }}-admin-role
  apiGroup: rbac.authorization.k8s.io
